interface Resources {
  "common": {
    "back": "back",
    "blog": "Blog",
    "button1": "Join waitlist",
    "button2": "Remind me",
    "formSubmitMemberExists": "Uh oh, it looks like this email's already subscribed🧐",
    "formSubmitSuccess": "Awesome! You have successfully subscribed!",
    "formSubmitWrongEmail": "Please enter a valid email address",
    "privacy": "Cookies & Privacy policy",
    "section1Subtitle": "We've got your back! Become one of the first smart travelers by joining our waitlist now.",
    "section1Title": "How to turn your trip idea into a reality?",
    "section2Subtitle": "From time constraints to information overload, finding the right destinations and routes can seem impossible.",
    "section2Title": "Planning a trip can feel like navigating in a maze",
    "section3CardSubtitle": "Begin by selecting the destination you wish to visit.",
    "section3CardTitle": "Choose your desired location",
    "section3Item1Subtitle": "The more information you provide, the better we can tailor your trip to your liking.",
    "section3Item1Title": "Share your travel preferences",
    "section3Item2Subtitle": "Sit back and relax as we create a customized trip itinerary just for you.",
    "section3Item2Title": "Voilà!",
    "section3Title": "Introducing\nZaplanuj Wypad",
    "section4Card1Subtitle": "Plan and execute your trip effortlessly, without the stress and uncertainty.",
    "section4Card1Title": "Seamless Trip Planning",
    "section4Card2Subtitle": "Embark on exciting journeys and discover hidden gems in new destinations.",
    "section4Card2Title": "Thrilling Adventures Await",
    "section4Card3Subtitle": "Efficient planning and cost-saving tips will make time and money work in your favor.",
    "section4Card3Title": "Time and Money on Your Side",
    "section4Sbtitle": "With Zaplanuj Wypad, you'll unlock a world of benefits!",
    "section4Title": "Say hello to effortless adventures!",
    "section5FormSubtitle": "By submitting this form, you confirm that you have read and agree to the <0>Terms & Conditions.<0>",
    "section5Subtitle": "Sign up for our waitlist today and be among the first to access our app!",
    "section5Title": "Don't miss out!",
    "section6Subtitle": "From adventure seekers to history buffs, foodies to culture vultures.",
    "section6Title": "We're a crew of engineer-explorers",
    "sectionRecentPostsTitle": "Recent Posts",
    "tag1": "AI-driven trip planner",
    "tag2": "Our solution",
    "tag3": "Dream team"
  }
}

export default Resources;
